name: Copy Files After Merge

on:
  push:
    branches:
      - main  # or the branch you're merging into 

jobs:
  copy-files:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy files using xcopy
        run: |
          $sourcePath = "C:\A"
          $destinationPath = "C:\B"
          robocopy $sourcePath $destinationPath /E
        shell: pwsh        
