name: Copy Files After Merge

on:
  push:
    branches:
      - main  # or the branch you're merging into

jobs:
  copy-files:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy files using xcopy
        run: |
          net use P: \\computer1\192.168.0.237\c$
          xcopy xcopy "P:\A\*" "P:\B\" /s /e /h /y
        shell: cmd