name: Copy Files to Windows Machine

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch 

jobs:
  copy-files:
    runs-on: windows-latest  # Use a Windows environment to interact with a Windows target machine

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH for Windows Machine
      - name: Set up SSH
        run: |
          mkdir -p C:\Users\runneradmin\.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | Out-File -FilePath C:\Users\runneradmin\.ssh\id_rsa -Force
          Set-ItemProperty -Path C:\Users\runneradmin\.ssh\id_rsa -Name IsReadOnly -Value $true
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> C:\Users\runneradmin\.ssh\known_hosts
        shell: pwsh

      # Step 3: Copy Files to the Windows Machine via SCP
      - name: Copy Files to Windows Machine
        run: |
          scp -r https://github.com/NihalSapineni/GitActions/tree/main/source/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:E$\GIT\GitActions\destination
        shell: pwsh
