on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: windows-latest

    steps:
    - name: Install SSH Keys
      run: |
        mkdir $env:USERPROFILE\.ssh
        $env:SSH_PRIVATE_KEY | Out-File -FilePath "$env:USERPROFILE\.ssh\id_rsa" -Encoding ascii
        icacls "$env:USERPROFILE\.ssh\id_rsa" /inheritance:r /grant:r "$env:USERNAME:(R,W)"
        ssh-keyscan -H ${{ secrets.SSH_HOST }} | Out-File -FilePath "$env:USERPROFILE\.ssh\known_hosts" -Encoding ascii

    - name: Connect and Pull
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} `
          "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
    
    - name: Cleanup
      run: |
        Remove-Item -Recurse -Force $env:USERPROFILE\.ssh
