name: Checkout Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print repository details
      run: echo ${{ secrets.SSH_PRIVATE_KEY }}
